version: '3.4'
services:
    model_downloader:
        build:
            context: .
        network_mode: host
        volumes:
            - $DOWNLOAD_DIR:/models
        working_dir: /opt/intel/openvino_2021/deployment_tools/tools/model_downloader
        command: "bash ./download_and_optimize.sh"

