ARG BASE_IMAGE="openvino/ubuntu20_dev:latest"
FROM ${BASE_IMAGE}
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /opt/intel/openvino_2021/deployment_tools/tools/model_downloader
COPY ./download_and_optimize.sh .
